//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:05:04 PM CEST 
//


package fr.cnes.sitools.xml.uws.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imageFormatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="imageFormatType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="image/fits"/>
 *     &lt;enumeration value="image/png"/>
 *     &lt;enumeration value="image/jpeg"/>
 *     &lt;enumeration value="image/gif"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "imageFormatType")
@XmlEnum
public enum ImageFormatType {

    @XmlEnumValue("image/fits")
    IMAGE_FITS("image/fits"),
    @XmlEnumValue("image/png")
    IMAGE_PNG("image/png"),
    @XmlEnumValue("image/jpeg")
    IMAGE_JPEG("image/jpeg"),
    @XmlEnumValue("image/gif")
    IMAGE_GIF("image/gif");
    private final String value;

    ImageFormatType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ImageFormatType fromValue(String v) {
        for (ImageFormatType c: ImageFormatType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
