//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:05:04 PM CEST 
//


package fr.cnes.sitools.xml.uws.v1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.cnes.sitools.xml.uws.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.cnes.sitools.xml.uws.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Rotation }
     * 
     */
    public InputsType.Geometry.Polygon.Rotation createInputsTypeGeometryPolygonRotation() {
        return new InputsType.Geometry.Polygon.Rotation();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Latitude2 }
     * 
     */
    public InputsType.Geometry.Polygon.Latitude2 createInputsTypeGeometryPolygonLatitude2() {
        return new InputsType.Geometry.Polygon.Latitude2();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Latitude4 }
     * 
     */
    public InputsType.Geometry.Polygon.Latitude4 createInputsTypeGeometryPolygonLatitude4() {
        return new InputsType.Geometry.Polygon.Latitude4();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Healpix.Order }
     * 
     */
    public InputsType.Geometry.Healpix.Order createInputsTypeGeometryHealpixOrder() {
        return new InputsType.Geometry.Healpix.Order();
    }

    /**
     * Create an instance of {@link OutputsType.Image }
     * 
     */
    public OutputsType.Image createOutputsTypeImage() {
        return new OutputsType.Image();
    }

    /**
     * Create an instance of {@link InputsType.Geometry }
     * 
     */
    public InputsType.Geometry createInputsTypeGeometry() {
        return new InputsType.Geometry();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Longitude4 }
     * 
     */
    public InputsType.Geometry.Polygon.Longitude4 createInputsTypeGeometryPolygonLongitude4() {
        return new InputsType.Geometry.Polygon.Longitude4();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Latitude3 }
     * 
     */
    public InputsType.Geometry.Polygon.Latitude3 createInputsTypeGeometryPolygonLatitude3() {
        return new InputsType.Geometry.Polygon.Latitude3();
    }

    /**
     * Create an instance of {@link InputsType }
     * 
     */
    public InputsType createInputsType() {
        return new InputsType();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Longitude1 }
     * 
     */
    public InputsType.Geometry.Polygon.Longitude1 createInputsTypeGeometryPolygonLongitude1() {
        return new InputsType.Geometry.Polygon.Longitude1();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Circle.Latitude }
     * 
     */
    public InputsType.Geometry.Circle.Latitude createInputsTypeGeometryCircleLatitude() {
        return new InputsType.Geometry.Circle.Latitude();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Longitude2 }
     * 
     */
    public InputsType.Geometry.Polygon.Longitude2 createInputsTypeGeometryPolygonLongitude2() {
        return new InputsType.Geometry.Polygon.Longitude2();
    }

    /**
     * Create an instance of {@link OutputsType }
     * 
     */
    public OutputsType createOutputsType() {
        return new OutputsType();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Circle.Longitude }
     * 
     */
    public InputsType.Geometry.Circle.Longitude createInputsTypeGeometryCircleLongitude() {
        return new InputsType.Geometry.Circle.Longitude();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Circle }
     * 
     */
    public InputsType.Geometry.Circle createInputsTypeGeometryCircle() {
        return new InputsType.Geometry.Circle();
    }

    /**
     * Create an instance of {@link InputsType.Keyword }
     * 
     */
    public InputsType.Keyword createInputsTypeKeyword() {
        return new InputsType.Keyword();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon }
     * 
     */
    public InputsType.Geometry.Polygon createInputsTypeGeometryPolygon() {
        return new InputsType.Geometry.Polygon();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Circle.Radius }
     * 
     */
    public InputsType.Geometry.Circle.Radius createInputsTypeGeometryCircleRadius() {
        return new InputsType.Geometry.Circle.Radius();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Healpix.Pixels }
     * 
     */
    public InputsType.Geometry.Healpix.Pixels createInputsTypeGeometryHealpixPixels() {
        return new InputsType.Geometry.Healpix.Pixels();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Longitude3 }
     * 
     */
    public InputsType.Geometry.Polygon.Longitude3 createInputsTypeGeometryPolygonLongitude3() {
        return new InputsType.Geometry.Polygon.Longitude3();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Healpix }
     * 
     */
    public InputsType.Geometry.Healpix createInputsTypeGeometryHealpix() {
        return new InputsType.Geometry.Healpix();
    }

    /**
     * Create an instance of {@link InputsType.Geometry.Polygon.Latitude1 }
     * 
     */
    public InputsType.Geometry.Polygon.Latitude1 createInputsTypeGeometryPolygonLatitude1() {
        return new InputsType.Geometry.Polygon.Latitude1();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link InputsType.Image }
     * 
     */
    public InputsType.Image createInputsTypeImage() {
        return new InputsType.Image();
    }

}
