/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * Any modifications to this file will be lost upon recompilation of the source schema. 
 * Generated on: 2013.10.03 at 10:05:04 PM CEST 
 *
 @javax.xml.bind.annotation.XmlSchema(namespace = "http://sitools.cnes.fr/xml/UWS/v1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
 */
package fr.cnes.sitools.xml.uws.v1;
