//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.11 at 11:48:30 PM CET 
//


package net.ivoa.xml.votable.v1;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.ivoa.xml.votable.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {

    private final static QName _TableLINK_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "LINK");
    private final static QName _TableDESCRIPTION_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "DESCRIPTION");
    private final static QName _TableGROUP_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "GROUP");
    private final static QName _TablePARAM_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "PARAM");
    private final static QName _TableFIELD_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "FIELD");
    private final static QName _TableDATA_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "DATA");
    private final static QName _TableINFO_QNAME = new QName("http://www.ivoa.net/xml/VOTable/v1.2", "INFO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.ivoa.xml.votable.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Values }
     * 
     */
    public Values createValues() {
        return new Values();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link AnyTEXT }
     * 
     */
    public AnyTEXT createAnyTEXT() {
        return new AnyTEXT();
    }

    /**
     * Create an instance of {@link Stream }
     * 
     */
    public Stream createStream() {
        return new Stream();
    }

    /**
     * Create an instance of {@link FITS }
     * 
     */
    public FITS createFITS() {
        return new FITS();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link FieldRef }
     * 
     */
    public FieldRef createFieldRef() {
        return new FieldRef();
    }

    /**
     * Create an instance of {@link CoordinateSystem }
     * 
     */
    public CoordinateSystem createCoordinateSystem() {
        return new CoordinateSystem();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Tr }
     * 
     */
    public Tr createTr() {
        return new Tr();
    }

    /**
     * Create an instance of {@link ParamRef }
     * 
     */
    public ParamRef createParamRef() {
        return new ParamRef();
    }

    /**
     * Create an instance of {@link TableData }
     * 
     */
    public TableData createTableData() {
        return new TableData();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Max }
     * 
     */
    public Max createMax() {
        return new Max();
    }

    /**
     * Create an instance of {@link VOTABLE }
     * 
     */
    public VOTABLE createVOTABLE() {
        return new VOTABLE();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Binary }
     * 
     */
    public Binary createBinary() {
        return new Binary();
    }

    /**
     * Create an instance of {@link Min }
     * 
     */
    public Min createMin() {
        return new Min();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link Resource }
     * 
     */
    public Resource createResource() {
        return new Resource();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Td }
     * 
     */
    public Td createTd() {
        return new Td();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "LINK", scope = Table.class)
    public JAXBElement<Link> createTableLINK(Link value) {
        return new JAXBElement<Link>(_TableLINK_QNAME, Link.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyTEXT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "DESCRIPTION", scope = Table.class)
    public JAXBElement<AnyTEXT> createTableDESCRIPTION(AnyTEXT value) {
        return new JAXBElement<AnyTEXT>(_TableDESCRIPTION_QNAME, AnyTEXT.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "GROUP", scope = Table.class)
    public JAXBElement<Group> createTableGROUP(Group value) {
        return new JAXBElement<Group>(_TableGROUP_QNAME, Group.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Param }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "PARAM", scope = Table.class)
    public JAXBElement<Param> createTablePARAM(Param value) {
        return new JAXBElement<Param>(_TablePARAM_QNAME, Param.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Field }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "FIELD", scope = Table.class)
    public JAXBElement<Field> createTableFIELD(Field value) {
        return new JAXBElement<Field>(_TableFIELD_QNAME, Field.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Data }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "DATA", scope = Table.class)
    public JAXBElement<Data> createTableDATA(Data value) {
        return new JAXBElement<Data>(_TableDATA_QNAME, Data.class, Table.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Info }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ivoa.net/xml/VOTable/v1.2", name = "INFO", scope = Table.class)
    public JAXBElement<Info> createTableINFO(Info value) {
        return new JAXBElement<Info>(_TableINFO_QNAME, Info.class, Table.class, value);
    }

}
