//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.13 at 12:27:53 AM CEST 
//


package fr.cnes.sitools.astro.resolver.cds;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.logging.Logger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

import org.restlet.engine.Engine;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An CDSFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class CDSFactory {

    private final static QName _ResolverVel_QNAME = new QName("", "Vel");
    private final static QName _ResolverMType_QNAME = new QName("", "MType");
    private final static QName _ResolverOname_QNAME = new QName("", "oname");
    private final static QName _ResolverAlias_QNAME = new QName("", "alias");
    private final static QName _ResolverJradeg_QNAME = new QName("", "jradeg");
    private final static QName _ResolverRefPos_QNAME = new QName("", "refPos");
    private final static QName _ResolverNrefs_QNAME = new QName("", "nrefs");
    private final static QName _ResolverErrDEmas_QNAME = new QName("", "errDEmas");
    private final static QName _ResolverSpType_QNAME = new QName("", "spType");
    private final static QName _ResolverErrRAmas_QNAME = new QName("", "errRAmas");
    private final static QName _ResolverOid_QNAME = new QName("", "oid");
    private final static QName _ResolverMag_QNAME = new QName("", "mag");
    private final static QName _ResolverERROR_QNAME = new QName("", "ERROR");
    private final static QName _ResolverPm_QNAME = new QName("", "pm");
    private final static QName _ResolverJpos_QNAME = new QName("", "jpos");
    private final static QName _ResolverPlx_QNAME = new QName("", "plx");
    private final static QName _ResolverJdedeg_QNAME = new QName("", "jdedeg");
    private final static QName _ResolverINFO_QNAME = new QName("", "INFO");
    private final static QName _ResolverOtype_QNAME = new QName("", "otype");
    private final static QName _ResolverSpNum_QNAME = new QName("", "spNum");
    private final static QName _ResolverZ_QNAME = new QName("", "z");

    /**
     * Create a new CDSFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public CDSFactory() {
    }

    /**
     * Create an instance of {@link Sesame }
     * 
     */
    public Sesame createSesame() {
        return new Sesame();
    }

    /**
     * Create an instance of {@link Target.Name }
     * 
     */
    public Target.Name createTargetName() {
        return new Target.Name();
    }

    /**
     * Create an instance of {@link PmVector }
     * 
     */
    public PmVector createPmVector() {
        return new PmVector();
    }

    /**
     * Create an instance of {@link Resolver }
     * 
     */
    public Resolver createResolver() {
        return new Resolver();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Veqr }
     * 
     */
    public Veqr createVeqr() {
        return new Veqr();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Veqr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vel", scope = Resolver.class)
    public JAXBElement<Veqr> createResolverVel(Veqr value) {
        return new JAXBElement<Veqr>(_ResolverVel_QNAME, Veqr.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MType", scope = Resolver.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResolverMType(String value) {
        return new JAXBElement<String>(_ResolverMType_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oname", scope = Resolver.class)
    public JAXBElement<String> createResolverOname(String value) {
        return new JAXBElement<String>(_ResolverOname_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "alias", scope = Resolver.class)
    public JAXBElement<String> createResolverAlias(String value) {
        return new JAXBElement<String>(_ResolverAlias_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jradeg", scope = Resolver.class)
    public JAXBElement<BigDecimal> createResolverJradeg(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ResolverJradeg_QNAME, BigDecimal.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "refPos", scope = Resolver.class)
    public JAXBElement<String> createResolverRefPos(String value) {
        return new JAXBElement<String>(_ResolverRefPos_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "nrefs", scope = Resolver.class)
    public JAXBElement<BigInteger> createResolverNrefs(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResolverNrefs_QNAME, BigInteger.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errDEmas", scope = Resolver.class)
    public JAXBElement<BigDecimal> createResolverErrDEmas(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ResolverErrDEmas_QNAME, BigDecimal.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spType", scope = Resolver.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResolverSpType(String value) {
        return new JAXBElement<String>(_ResolverSpType_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "errRAmas", scope = Resolver.class)
    public JAXBElement<BigDecimal> createResolverErrRAmas(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ResolverErrRAmas_QNAME, BigDecimal.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "oid", scope = Resolver.class)
    public JAXBElement<BigInteger> createResolverOid(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResolverOid_QNAME, BigInteger.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Veqr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mag", scope = Resolver.class)
    public JAXBElement<Veqr> createResolverMag(Veqr value) {
        return new JAXBElement<Veqr>(_ResolverMag_QNAME, Veqr.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ERROR", scope = Resolver.class)
    public JAXBElement<String> createResolverERROR(String value) {
        return new JAXBElement<String>(_ResolverERROR_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmVector }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pm", scope = Resolver.class)
    public JAXBElement<PmVector> createResolverPm(PmVector value) {
        return new JAXBElement<PmVector>(_ResolverPm_QNAME, PmVector.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jpos", scope = Resolver.class)
    public JAXBElement<String> createResolverJpos(String value) {
        return new JAXBElement<String>(_ResolverJpos_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Veqr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plx", scope = Resolver.class)
    public JAXBElement<Veqr> createResolverPlx(Veqr value) {
        return new JAXBElement<Veqr>(_ResolverPlx_QNAME, Veqr.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jdedeg", scope = Resolver.class)
    public JAXBElement<BigDecimal> createResolverJdedeg(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ResolverJdedeg_QNAME, BigDecimal.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INFO", scope = Resolver.class)
    public JAXBElement<String> createResolverINFO(String value) {
        return new JAXBElement<String>(_ResolverINFO_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "otype", scope = Resolver.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResolverOtype(String value) {
        return new JAXBElement<String>(_ResolverOtype_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "spNum", scope = Resolver.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResolverSpNum(String value) {
        return new JAXBElement<String>(_ResolverSpNum_QNAME, String.class, Resolver.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Veqr }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "z", scope = Resolver.class)
    public JAXBElement<Veqr> createResolverZ(Veqr value) {
        return new JAXBElement<Veqr>(_ResolverZ_QNAME, Veqr.class, Resolver.class, value);
    }
    private static final Logger LOG = Engine.getLogger(CDSFactory.class.getName());

}
