//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.13 at 12:27:53 AM CEST 
//


package fr.cnes.sitools.astro.resolver.cds;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="INFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ERROR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="oid" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="otype" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="jpos" type="{}sexapos"/>
 *         &lt;element name="jradeg" type="{}lon"/>
 *         &lt;element name="jdedeg" type="{}lat"/>
 *         &lt;element name="refPos" type="{}bibcode"/>
 *         &lt;element name="errRAmas" type="{}err"/>
 *         &lt;element name="errDEmas" type="{}err"/>
 *         &lt;element name="pm" type="{}pmVector"/>
 *         &lt;element name="MType" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="spType" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="spNum" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="Vel" type="{}veqr"/>
 *         &lt;element name="z" type="{}veqr"/>
 *         &lt;element name="mag" type="{}veqr"/>
 *         &lt;element name="plx" type="{}veqr"/>
 *         &lt;element name="oname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nrefs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "infoOrERROROrOid"
})
@XmlRootElement(name = "Resolver")
public class Resolver {

    @XmlElementRefs({
        @XmlElementRef(name = "spNum", type = JAXBElement.class),
        @XmlElementRef(name = "mag", type = JAXBElement.class),
        @XmlElementRef(name = "otype", type = JAXBElement.class),
        @XmlElementRef(name = "alias", type = JAXBElement.class),
        @XmlElementRef(name = "z", type = JAXBElement.class),
        @XmlElementRef(name = "errDEmas", type = JAXBElement.class),
        @XmlElementRef(name = "jdedeg", type = JAXBElement.class),
        @XmlElementRef(name = "refPos", type = JAXBElement.class),
        @XmlElementRef(name = "Vel", type = JAXBElement.class),
        @XmlElementRef(name = "oname", type = JAXBElement.class),
        @XmlElementRef(name = "oid", type = JAXBElement.class),
        @XmlElementRef(name = "INFO", type = JAXBElement.class),
        @XmlElementRef(name = "spType", type = JAXBElement.class),
        @XmlElementRef(name = "jpos", type = JAXBElement.class),
        @XmlElementRef(name = "ERROR", type = JAXBElement.class),
        @XmlElementRef(name = "jradeg", type = JAXBElement.class),
        @XmlElementRef(name = "plx", type = JAXBElement.class),
        @XmlElementRef(name = "MType", type = JAXBElement.class),
        @XmlElementRef(name = "nrefs", type = JAXBElement.class),
        @XmlElementRef(name = "errRAmas", type = JAXBElement.class),
        @XmlElementRef(name = "pm", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> infoOrERROROrOid;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String code;

    /**
     * Gets the value of the infoOrERROROrOid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infoOrERROROrOid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getINFOOrERROROrOid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Veqr }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Veqr }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Veqr }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link Veqr }{@code >}
     * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PmVector }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getINFOOrERROROrOid() {
        if (infoOrERROROrOid == null) {
            infoOrERROROrOid = new ArrayList<JAXBElement<?>>();
        }
        return this.infoOrERROROrOid;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

}
